---
title: "numeric_eda"
author: "Elaine Yanxi Chen"
date: 2022-10-06
output: 
  github_document
    

    
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Let's import data

```{r}
library(tidyverse)
```

Copy code from the course website to download data.

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())

weather_df %>% view
```


## `group_by()`

```{r}
weather_df %>% 
  group_by(name, month)
```

## `summarize()`

let's group and then summarize!

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs = n()
  )
```

can we count in other ways?

```{r}
weather_df %>% 
  count(name, month)
```

don't use `table()` because it doesn't form a dataframe 

```{r, eval = FALSE}
weather_df %>% 
  pull(month) %>% 
  table()
```


you can have multiple summaries

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    n_obs = n(),
    n_dist = n_distinct()
  )
```

